name: scraper-wm-indices-yahoo-finance

on:
  workflow_dispatch:
  schedule:
    - cron: '1,7,13,19,25,31,37,43,49,55 12 * * 1-5' # runs four times an hour between 11am and 1pm UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
          
      - name: execute py script 
        run: pipenv run python worldMarketIndicesUpdate.py
        env: 
          DW_API_KEY: ${{ secrets.DW_API_KEY }}
        
          
      - name: commit & push files
        run: |
          git pull
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "Automated"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest World Market Indices Update: ${timestamp}" || exit 0
          git push